//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplicationEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Salary
    {
        public Nullable<int> Emp_Id { get; set; }
        public Nullable<int> Emp_Salary1 { get; set; }
        public string Emp_Designation { get; set; }
        public int Emp_Sal_Id { get; set; }
    }
}
